### ISSUE TITLE
I run the app module of this project, and input "123" ,but it can't be scanned by other qr scanner.

### ISSUE THREAD

**Issue by duweiwang** [alexzhirkevich/custom-qr-generator#47]
**Describe the option you are trying to implement**

I want to create QR code with ....

**Example**

Attach an example of QR code you want to have, if possible.

**Comment by duweiwang** [comment]
<img width="418" alt="image" src="https://github.com/alexzhirkevich/custom-qr-generator/assets/89289580/64bbffb7-571a-4e8a-95ec-0b106b4f87c4">

**Comment by alexzhirkevich** [comment]
In this paticular case logo is too big. Make it smaller. Also [this readme section will be useful to read](https://github.com/alexzhirkevich/custom-qr-generator#i-cant-scan-my-code)

**Comment by duweiwang** [comment]
Thanks a lot,  I have solved this by "Set errorCorrectionLevel explicitly to QrErrorCorrectionLevel.High"  In my app.

**Comment by hardikbhalodi** [comment]
in above case problem is the eyes because eyes must be clearly visible. your background line colour and eyes colour same and overlapping. check the below example. it can be achieve like this.

![telegram](https://github.com/alexzhirkevich/custom-qr-generator/assets/4948894/905cf4e8-d76a-41fc-9813-a8a677c0f051)
